describe('Magic Link v2 — user-switch behaviour', () => {
  // Links generated by the Java test and passed via environment variables.
  // linkA is reusable so it can be used to establish a User A session in each test.
  const linkA       = () => Cypress.env('LINK_USER_A') as string;
  const linkBNoConf = () => Cypress.env('LINK_USER_B_AUTO') as string;
  const linkBConf   = () => Cypress.env('LINK_USER_B_CONFIRM') as string;
  const linkBCancel = () => Cypress.env('LINK_USER_B_CANCEL') as string;

  /**
   * Establishes a Keycloak session for User A by following their magic link.
   * Must be called at the start of each test that requires a logged-in User A.
   */
  function loginAsUserA() {
    cy.visit(linkA(), { failOnStatusCode: false });
    cy.url().should('include', 'code=');
  }

  it('auto-logout (default): silently logs out current user and authenticates target user', () => {
    loginAsUserA();

    // User A is now logged in. Opening User B's link (no confirm_user_switch) should
    // expire User A's session cookies, redirect to a fresh auth flow, and return an
    // authorization code for User B — without showing any confirmation screen.
    cy.visit(linkBNoConf(), { failOnStatusCode: false });
    cy.url().should('include', 'code=');
  });

  it('confirm_user_switch=true: shows confirmation form with Sign out and Cancel options', () => {
    loginAsUserA();

    // User A is logged in. Opening User B's link with confirm_user_switch=true should
    // render the user-switch confirmation page instead of logging out automatically.
    cy.visit(linkBConf(), { failOnStatusCode: false });
    cy.get('#kc-logout').should('be.visible');
    cy.get('#kc-cancel').should('be.visible');

    // Clicking "Sign out and continue" should perform the logout and complete the flow.
    cy.get('#kc-logout').click();
    cy.url().should('include', 'code=');
  });

  it('confirm_user_switch=true: Cancel redirects back to client with error=access_denied', () => {
    loginAsUserA();

    cy.visit(linkBCancel(), { failOnStatusCode: false });
    cy.get('#kc-cancel').should('be.visible');

    // Cancelling should abort the flow and redirect to the redirect_uri with
    // error=access_denied per the OIDC spec.
    cy.get('#kc-cancel').click();
    cy.url().should('include', 'error=access_denied');
  });
});
