describe('Basic tests when the Magic Link was generated by an external service', () => {
   it('Opening Magic Link should load the account console', () => {
      const generatedMagicLinkValue = Cypress.env('generatedMagicLink')
      cy.task('log', 'The magic link we got from the Java code is: ' + generatedMagicLinkValue);
      cy.visit(generatedMagicLinkValue);
      cy.url().should('contain', 'test-realm')
      cy.contains('Personal')
   })
});